### ISSUE TITLE
Bard songs issue

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/iwdification#11]
On oBG2, don't know for EE, there is a strange behaviour with new bard song: they work I/O every round. In words, when activated, the first round works fine, at stratstart of the second round it stops, and at stratstart of the third round it restarts and works fine, etc...

This bug seems to be linked to how works the opcode 206. setting offset 0x92 h (Offset to feature blocks) to 0 seems to solve this bug for :

    The Ballad of Three Heroes
    The Tale of Curran Strongheart
    Tymora's Melody
    The Song of Kaudies
    War Chant of Sith

for The Siren's Yearning, the offset solution does not work alone. However removing the 206 opcode for self-protection (it does not seem to be needed as the spell target only ennemies) from this spell, in addition to setting the 0x92 offset set to 0, seem to solve the issue with this one.

**This solution seem to have a compatibility issue with mods that modified spl. when the song is updated the offset 0x92 h (Offset to feature blocks) is set back to 1, no matter what...** 

In addition the SPCLxxx (bard song spell) seem to have wrong `Ability location` : I think that it should be `Ability` and not `Spell`

**Comment by TotoR115** [comment]
Don't know if it is on purpose but when using bard song on oBG2 (maybe also for EE) the following information in the text field appear every round:

> Singing Battlesong
> The Ballad of Three Heroes—Combat Bonuses

Instead of classicly:

> Singing Battlesong

This is linked to the fact that the spclxxx (bard song spell) have a `Spell Name` and seem a bit odd.

**Comment by CamDawg** [comment]
This is fixed in https://github.com/Gibberlings3/iwdification/commit/b0abb5a63098070711fc4c88ab15733647db5d09

Long story short, the songs were lasting just over a round, so the previous round's 206 would block the next round's effects. 

As for the name, this is intended and also how it works on IWD. Since there are multiple bard songs available, having the name in the combat log is needed to distinguish which song is active.
